/**
	Generated by sails-inverse-model
	Date:Wed Oct 24 2018 19:35:40 GMT-0500 (Central Daylight Time)
*/

module.exports = {
  attributes: {

    //  ╔═╗╦═╗╦╔╦╗╦╔╦╗╦╦  ╦╔═╗╔═╗
    //  ╠═╝╠╦╝║║║║║ ║ ║╚╗╔╝║╣ ╚═╗
    //  ╩  ╩╚═╩╩ ╩╩ ╩ ╩ ╚╝ ╚═╝╚═╝

    name: {
      type: 'string',
    },
    hoverStats: {
      type: 'string',
    },
    karma: {
      type: 'string',
    },
    gold: {
      type: 'string',
    },
    alignment: {
      type: 'string',
    },
    hp: {
      type: 'string',
    },
    bard: {
      type: 'string',
    },
    taming: {
      type: 'string',
    },
    resistF: {
      type: 'string',
    },
    resistC: {
      type: 'string',
    },
    resistP: {
      type: 'string',
    },
    resistE: {
      type: 'string',
    },
    resistPh: {
      type: 'string',
    },
    magery: {
      type: 'string',
    },
    evalInt: {
      type: 'string',
    },
    aggroPriority: {
      type: 'number',
    },
    tactics: {
      type: 'string',
    },
    resistSpell: {
      type: 'string',
    },
    anatomy: {
      type: 'string',
    },
    strength: {
      type: 'string',
    },
    dexterity: {
      type: 'string',
    },
    intelligence: {
      type: 'string',
    },
    baseDmg: {
      type: 'string',
    },
    preferredFood: {
      type: 'string',
    },
    controlSlots: {
      type: 'number',
    },
    specials: {
      type: 'string',
    },

    //TODO: remove these fields when we have our bootstrap data finalized and we no longer need to do --drop
    goldMin: {
      type: 'number',
    },
    goldMax: {
      type: 'number',
    },
    hpMin: {
      type: 'number',
    },
    hpMax: {
      type: 'number',
    },
    bardMin: {
      type: 'number',
    },
    bardMax: {
      type: 'number',
    },
    fireMin: {
      type: 'number',
    },
    fireMax: {
      type: 'number',
    },
    coldMin: {
      type: 'number',
    },
    coldMax: {
      type: 'number',
    },
    poisonMin: {
      type: 'number',
    },
    poisonMax: {
      type: 'number',
    },
    energyMin: {
      type: 'number',
    },
    energyMax: {
      type: 'number',
    },
    physicalMin: {
      type: 'number',
    },
    physicalMax: {
      type: 'number',
    },
    mageryMin: {
      type: 'number',
    },
    mageryMax: {
      type: 'number',
    },
    evalIntMin: {
      type: 'number',
    },
    evalIntMax: {
      type: 'number',
    },
    tacticsMin: {
      type: 'number',
    },
    tacticsMax: {
      type: 'number',
    },
    resistSpellMin: {
      type: 'number',
    },
    resistSpellMax: {
      type: 'number',
    },
    anatomyMin: {
      type: 'number',
    },
    anatomyMax: {
      type: 'number',
    },
    strengthMin: {
      type: 'number',
    },
    strengthMax: {
      type: 'number',
    },
    dexterityMin: {
      type: 'number',
    },
    dexterityMax: {
      type: 'number',
    },
    intelligenceMin: {
      type: 'number',
    },
    intelligenceMax: {
      type: 'number',
    },
    baseDmgMin: {
      type: 'number',
    },
    baseDmgMax: {
      type: 'number',
    },


    //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
    //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
    //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝


    //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
    //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
    //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝

    actions: { collection: 'monsteraction', via: 'monster' },
    damageType: { model: 'damagetype' },
    breathDmgType: { model: 'damagetype' },
    slayers: { collection: 'slayertype', via: 'monsters' }

  }
};
